# Generated by Django 3.0.6 on 2020-05-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiskSchedAlg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('demourl', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('alg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discsch.DiskSchedAlg')),
            ],
        ),
    ]
